const SHEETS_URL = 'https://script.google.com/macros/s/AKfycbyv0UhVSiM52K-g8A31Myih_UMMGKhZIwRAAMcMW_3WwYofjgtNCV-6J7p6iv0ODSsU/exec/exec';
function openPanel(id){document.getElementById('home').style.display='none';document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.getElementById('panel-'+id).classList.add('active');window.scrollTo(0,0)}
function goHome(){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.getElementById('home').style.display='block';window.scrollTo(0,0)}
function closeModal(id,e){if(e.target===document.getElementById(id))document.getElementById(id).classList.remove('open')}
const rankingData=[{pos:1,nome:'Beatriz Ferreira',nivel:'Explorador 🧭',pts:0,medal:'🥇'},{pos:2,nome:'Daniel Lucena',nivel:'Explorador 🧭',pts:0,medal:'🥈'},{pos:3,nome:'Joyce Souza',nivel:'Explorador 🧭',pts:0,medal:'🥉'}]
document.getElementById('rankMini').innerHTML=rankingData.map(r=>`<div class="rank-mini-row"><div class="rank-medal">${r.medal}</div><div class="rank-name-text">${r.nome}</div><div class="rank-level-badge">${r.nivel}</div><div class="rank-pts-mini">${r.pts}</div></div>`).join('')
document.getElementById('rankingList').innerHTML=rankingData.map(r=>`<div class="rank-row"><div class="rank-pos-num ${r.pos<=3?'g'+r.pos:''}">${r.medal}</div><div class="rank-info"><div class="rank-pname">${r.nome}</div><div class="rank-plevel">${r.nivel}</div></div><div class="rank-ppts">${r.pts} pts</div></div>`).join('')
const profiles=[{emoji:'🏃',name:'Corredor Iniciante',tag:'Está começando a correr, quer monitorar progresso',tags:['Corrida','Iniciante','GPS'],sinais:['Menciona que começou a correr recentemente','Usa tênis de corrida mas não tem relógio esportivo','Fala em 5km, 10km, primeira corrida de rua'],comunicacao:['Foque em GPS + frequência cardíaca','Mostre o Garmin Connect e como registra a evolução'],produtos:['Forerunner 55','Forerunner 165'],primario:'Forerunner 55',objections:[{q:'Preciso mesmo de GPS se o celular já tem?',a:'O GPS do celular perde precisão. No relógio fica no pulso e mostra ritmo em tempo real.'}]}]
function renderProfiles(arr){document.getElementById('profilesGrid').innerHTML=arr.map((p,i)=>`<div class="profile-card" onclick="openProfileModal(${i})"><div class="profile-card-top"><div class="p-emoji">${p.emoji}</div><div class="p-name">${p.name}</div><div class="p-tag">${p.tag}</div></div><div class="profile-card-body"><div class="p-sinais-label">Sinais de identificação</div><ul class="p-sinais">${p.sinais.slice(0,3).map(s=>`<li>${s}</li>`).join('')}</ul></div><div class="profile-card-footer"><div class="p-prods-label">Produtos indicados</div>${p.produtos.map(pr=>`<span class="prod-pill ${pr===p.primario?'main':''}">${pr}</span>`).join('')}</div></div>`).join('')}
function filterProfiles(){const q=document.getElementById('profileSearch').value.toLowerCase();renderProfiles(q?profiles.filter(p=>p.name.toLowerCase().includes(q)||p.tag.toLowerCase().includes(q)||p.tags.some(t=>t.toLowerCase().includes(q))||p.produtos.some(pr=>pr.toLowerCase().includes(q))):profiles)}
function openProfileModal(i){const p=profiles[i];document.getElementById('profileModalContent').innerHTML=`<div class="modal-emoji">${p.emoji}</div><div class="modal-title">${p.name}</div><div class="modal-sub">${p.tag}</div><div style="margin-bottom:14px;">${p.tags.map(t=>`<span class="tag blue">${t}</span>`).join('')}</div><div class="modal-section"><h4>Como identificar</h4><ul>${p.sinais.map(s=>`<li>${s}</li>`).join('')}</ul></div><div class="modal-section"><h4>Como se comunicar</h4><ul>${p.comunicacao.map(c=>`<li>${c}</li>`).join('')}</ul></div><div class="modal-section"><h4>Objeções comuns</h4>${p.objections.map(o=>`<div class="obj-block"><div class="obj-q">🗣️ ${o.q}</div><div class="obj-a">✅ ${o.a}</div></div>`).join('')}</div><div class="modal-section"><h4>Produtos indicados</h4><div>${p.produtos.map(pr=>`<span class="prod-pill ${pr===p.primario?'main':''}">${pr}</span>`).join('')}</div></div>`;document.getElementById('profileModal').classList.add('open')}
renderProfiles(profiles)
const prods=[{name:'Forerunner 55',s:'Forerunner',cat:'forerunner',lvl:1,para:'Corredor Iniciante',dest:'GPS + cardíaco óptico. Porta de entrada perfeita.'},{name:'Forerunner 165',s:'Forerunner',cat:'forerunner',lvl:2,para:'Corredor Iniciante / Dedicado',dest:'AMOLED + planos de treino.'},{name:'Venu 4',s:'Venu',cat:'lifestyle',lvl:3,para:'Mulher Lifestyle / Bem-estar',dest:'AMOLED premium + saúde feminina completa.'},{name:'Instinct 3',s:'Instinct',cat:'outdoor',lvl:3,para:'Aventureiro / Corredor',dest:'MIL-STD-810. Bateria até 26 dias.'},{name:'GPSMAP 67',s:'GPSMAP',cat:'gps',lvl:4,para:'Expedição / Aventureiro',dest:'Tela maior + altímetro + bússola + barômetro.'},{name:'Striker Vivid 5cv',s:'Striker',cat:'marine',lvl:2,para:'Pescador',dest:'ClearVü + SideVü + GPS.'},{name:'Approach S50',s:'Approach',cat:'golf',lvl:3,para:'Golfista Dedicado',dest:'AMOLED + +42.000 campos.'},{name:'Zumo XT2',s:'Zumo',cat:'moto',lvl:4,para:'Motociclista',dest:'GPS para moto.'}]
function renderProds(filter){const f=filter==='todos'?prods:prods.filter(p=>p.cat===filter);document.getElementById('prodsBody').innerHTML=f.map(p=>{const dots=Array.from({length:5},(_,i)=>`<div class="ld ${i<p.lvl?'on':''}"></div>`).join('');return`<tr><td><div class="prod-name">${p.name}</div><span class="prod-series">${p.s}</span></td><td><div class="level-dots">${dots}</div></td><td>${p.para}</td><td>${p.dest}</td></tr>`}).join('')}
function filterProds(cat,btn){document.querySelectorAll('.fbtn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderProds(cat)}
renderProds('todos')
const faqs=[{q:'Qual a diferença entre Garmin Connect e Connect IQ?',a:'Garmin Connect sincroniza dados; Connect IQ é a loja de apps do relógio.'}]
function renderFaq(){document.getElementById('faqList').innerHTML=faqs.map((f,i)=>`<div class="acc-item" id="faq-${i}"><button class="acc-btn" onclick="toggleAcc(this)"><span>${f.q}</span></button><div class="acc-body">${f.a}</div></div>`).join('')}
function toggleAcc(el){el.closest('.acc-item').classList.toggle('open')}
renderFaq()
const sports=[{emoji:'🏃',name:'Corrida',metrics:['Distância','Ritmo','Cadência','FC']},{emoji:'🚴',name:'Ciclismo',metrics:['Distância','Velocidade','Cadência','Potência']},{emoji:'🏊',name:'Natação',metrics:['Distância','Ritmo','Braçadas']},{emoji:'🏔️',name:'Trilha',metrics:['Distância','Subida','FC']},{emoji:'⛳',name:'Golfe',metrics:['Scorecard','Distâncias','Handicap']},{emoji:'🤿',name:'Mergulho',metrics:['Profundidade','Tempo de fundo','NDL']}]
document.getElementById('sportsList').innerHTML=sports.map(s=>`<div class="sport-card"><div class="sport-header"><div class="sport-emoji">${s.emoji}</div><div class="sport-name">${s.name}</div></div><div class="metrics-wrap">${s.metrics.map(m=>`<span class="tag">${m}</span>`).join('')}</div></div>`).join('')
const certs=[{emoji:'🧭',level:'Nível 1',name:'Explorador',color:'#007CC3',unlocked:true,obj:'Dominar o portfólio básico Garmin.',skills:['Identificar perfis','Apresentar o produto certo'],mods:[{n:1,t:'O Universo Garmin',c:'História, posicionamento e DNA da marca.'},{n:2,t:'Perfis de Cliente',c:'Como identificar e comunicar.'}]}]
document.getElementById('certList').innerHTML=certs.map((c,i)=>`<div class="cert-card ${c.unlocked?'unlocked':'locked'}" ${c.unlocked?`onclick="openCertModal(${i})"`:''}><div class="cert-header"><div class="cert-emoji">${c.emoji}</div><div><div class="cert-level-text">${c.level}</div><div class="cert-name-text">${c.name}</div></div></div><div class="cert-stripe" style="background:linear-gradient(90deg,${c.color},transparent)"></div><div class="cert-body"><div class="cert-obj">${c.obj}</div></div></div>`).join('')
function openCertModal(i){const c=certs[i];document.getElementById('certModalContent').innerHTML=`<div style="font-size:40px;margin-bottom:8px;">${c.emoji}</div><div class="modal-title">${c.name}</div><div class="modal-section"><h4>Objetivo</h4><p>${c.obj}</p></div>`;document.getElementById('certModal').classList.add('open')}
const quizData=[{q:'Em que ano a Garmin foi fundada?',opts:['1985','1989','1993','1999'],correct:1,exp:'A Garmin foi fundada em 1989.'},{q:'O que significa o nome Garmin?',opts:['Sigla de GPS','Gary + Min','Cidade do Kansas','Palavra japonesa'],correct:1,exp:'GAR + MIN = Garmin.'}]
let currentQ=0,score=0,answered=false
function initQuiz(){currentQ=0;score=0;answered=false;renderQuestion()}
function renderQuestion(){const q=quizData[currentQ];document.getElementById('quizBar').style.width=((currentQ)/quizData.length)*100+'%';document.getElementById('quizContent').innerHTML=`<div class="quiz-q-num">Pergunta ${currentQ+1} de ${quizData.length}</div><div class="quiz-q">${q.q}</div><div class="quiz-options">${q.opts.map((o,i)=>`<button class="quiz-opt" onclick="answerQ(${i})">${o}</button>`).join('')}</div><div class="quiz-feedback" id="quizFeedback"></div><div style="display:flex;justify-content:flex-end;margin-top:16px;"><button class="quiz-btn" id="nextBtn" onclick="nextQ()" disabled>${currentQ<quizData.length-1?'Próxima →':'Ver Resultado'}</button></div>`;answered=false}
function answerQ(i){if(answered)return;answered=true;const q=quizData[currentQ];const opts=document.querySelectorAll('.quiz-opt');const fb=document.getElementById('quizFeedback');if(i===q.correct){opts[i].style.borderColor='var(--acc)';fb.className='quiz-feedback show ok';fb.textContent='✅ Correto! '+q.exp;score++}else{opts[i].style.borderColor='var(--warn)';opts[q.correct].style.borderColor='var(--acc)';fb.className='quiz-feedback show fail';fb.textContent='❌ Incorreto. '+q.exp}document.getElementById('nextBtn').disabled=false}
function nextQ(){currentQ++;if(currentQ<quizData.length)renderQuestion();else showResult()}
function showResult(){document.getElementById('quizBar').style.width='100%';const pct=Math.round(score/quizData.length*100);document.getElementById('quizContent').innerHTML=`<div style="text-align:center;padding:20px 0;"><div style="font-size:56px;margin-bottom:12px;">🎉</div><div style="font-family:'Rajdhani',sans-serif;font-weight:700;font-size:28px;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px;color:var(--acc)">Aprovado!</div><div style="font-size:16px;color:var(--text2);margin-bottom:20px;">Você acertou <strong>${score}</strong> de ${quizData.length} questões — <strong>${pct}%</strong></div><div class="register-form"><label class="register-label">📝 Registre sua conclusão</label><input type="text" class="register-input" id="regName" placeholder="Seu nome"><button class="register-btn" onclick="registerResult(${pct})">Registrar Conclusão ✓</button><div class="register-success" id="regSuccess">✅ Registrado com sucesso!</div></div></div>`}
async function registerResult(pct){const name=document.getElementById('regName').value.trim();if(!name)return alert('Informe seu nome');const response=await fetch(SHEETS_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome:name,modulo:'Módulo 1 — Universo Garmin',nota:pct,acertos:score,total:quizData.length,origem:'Garmin Training Site'})});const data=await response.json().catch(()=>({}));if(data.success)document.getElementById('regSuccess').style.display='block';else alert('Erro ao registrar')}
initQuiz()
window.addEventListener('load',()=>{const hash=location.hash.replace('#','');if(hash&&document.getElementById('panel-'+hash))openPanel(hash)})
