-- ============================================================================
-- GARMIN TRAINING HUB — SEED 040: BIBLIOTECA TÉCNICA (content_library)
-- ============================================================================
-- Migração de dados reais do protótipo estático index_redesign_v5.html para a
-- tabela genérica content_library (ver sql/002_content_library_schema.sql).
-- Fonte: arrays JS "profiles", "prods", "faqs", "comps" e "sports" do protótipo.
--
-- Cobertura desta seed (contagem real dos arrays de origem, na data da migração):
--   perfil_cliente  : 11 personas de cliente
--   produto         : 53 produtos do catálogo
--   faq             : 16 perguntas frequentes
--   concorrente     : 5 comparativos com concorrentes
--   especialidade   : 10 especialidades por esporte
--   TOTAL           : 95 linhas
--
-- payload jsonb guarda fielmente TODOS os campos originais do objeto JS de cada
-- item (nomes de chave mantidos como no protótipo: emoji, tag, sinais, comunicacao,
-- produtos, primario, objections, s, cat, lvl, para, dest, q, a, badge, bc, desc,
-- rows, metrics — conforme a categoria). Nada foi resumido, traduzido ou inventado.
--
-- Pré-requisito: garmin_training_hub_migrations.sql (tabela brands) e
-- sql/002_content_library_schema.sql (tabela content_library) já aplicados.
-- ============================================================================

-- ============================================================================
-- 1. PERFIS DE CLIENTE (category = 'perfil_cliente') — 11 personas
-- ============================================================================
insert into content_library (brand_id, category, slug, title, summary, payload, order_index, is_published) values
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'corredor-iniciante', 'Corredor Iniciante', 'Começa a correr agora ou retorna ao esporte', '{"emoji":"🏃","name":"Corredor Iniciante","tag":"Começa a correr agora ou retorna ao esporte","tags":["Corrida","Iniciante","GPS"],"sinais":["Nunca usou relógio GPS","Fala de \"começar a correr\"","Pergunta o modelo mais simples","Quer monitorar tempo e distância"],"comunicacao":["Forerunner 55 é a porta de entrada ideal","Forerunner 165 para quem quer tela AMOLED premium desde o início","Fale dos planos de treino adaptativos: é como ter um técnico","Mostre como sincroniza com o celular facilmente"],"produtos":["Forerunner 55","Forerunner 165"],"primario":"Forerunner 55","objections":[{"q":"Tá caro, vou pesquisar online.","a":"Entendo perfeitamente. Mas aqui você tem garantia direta com a Proparts — importadora oficial —, suporte técnico presencial e pode experimentar agora."},{"q":"Preciso de todas essas funções?","a":"O FR55 tem exatamente o que você precisa para começar: GPS, frequência cardíaca e treinos básicos. Sem complicação — você aprende a usar em minutos."}]}'::jsonb, 0, true),
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'corredor-dedicado', 'Corredor Dedicado', 'Treina com frequência e busca evolução', '{"emoji":"🏅","name":"Corredor Dedicado","tag":"Treina com frequência e busca evolução","tags":["Corrida","Intermediário","Métricas"],"sinais":["Já usa relógio com GPS básico","Corre 3+ vezes por semana","Fala em ritmo, treino intervalado, PR","Pergunta por precisão e métricas mais avançadas"],"comunicacao":["FR265 ou 570 — GPS multibanda e métricas completas","Fale do Training Readiness: saber o dia certo para treinar forte","PacePRO para quem quer estratégia de prova","Destaque o ecossistema: Strava, TrainingPeaks, Stryd"],"produtos":["Forerunner 265","Forerunner 570","Forerunner 965"],"primario":"Forerunner 265","objections":[{"q":"O FR165 já não é suficiente?","a":"O FR165 é ótimo para iniciar. O FR265 adiciona GPS multibanda — muito mais preciso em cidades."},{"q":"Qual a diferença real do 265 pro 570?","a":"O 570 é o lançamento 2025 com sensor óptico de 5ª geração (Elevate Gen 5), mais preciso em alta intensidade."}]}'::jsonb, 1, true),
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'atleta-de-elite-triatleta', 'Atleta de Elite / Triatleta', 'Alto volume de treino, competições, multiesporte', '{"emoji":"🏆","name":"Atleta de Elite / Triatleta","tag":"Alto volume de treino, competições, multiesporte","tags":["Corrida","Triathlon","Elite","Natação","Ciclismo"],"sinais":["Menciona triathlon, Ironman, ultra","Pergunta por bateria longa e GPS preciso","Já tem relógio mas quer upgrade","Treina mais de 10h por semana"],"comunicacao":["FR955 ou 965 — ferramentas de triatleta","Fenix 8 para quem também faz outdoor","Bateria 30h+ GPS real, não estimada","Training Readiness para periodização"],"produtos":["Forerunner 955","Forerunner 965","Forerunner 970","Fenix 8"],"primario":"Forerunner 970","objections":[{"q":"O FR955 não mudou muito do 945.","a":"O 955 trouxe GPS multibanda, sensor HRV Status, Training Readiness e carregamento solar."},{"q":"Fenix ou FR970?","a":"O FR970 é o top de corrida — cristal de safira, lanterna LED integrada, 32GB. O Fenix 8 adiciona alto-falante, mic, mergulho."}]}'::jsonb, 2, true),
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'aventureiro-trilheiro', 'Aventureiro / Trilheiro', 'Ama trilhas, camping, aventura outdoor', '{"emoji":"🌿","name":"Aventureiro / Trilheiro","tag":"Ama trilhas, camping, aventura outdoor","tags":["Trilha","Outdoor","Trekking","Aventura"],"sinais":["Fala de trilha, serra, montanha","Pergunta por GPS com mapa topográfico","Quer algo resistente e com bateria longa","Menciona acampamento ou expedição"],"comunicacao":["Instinct 3 — MIL-STD-810, certificação militar de robustez, bateria 26 dias","Fenix 8 para quem quer o máximo em outdoor e também faz esporte","Destaque mapas TopoActive e trilhas offline","Inclua o inReach para expedições longas sem sinal"],"produtos":["Instinct 3","Fenix 8","Enduro 3"],"primario":"Instinct 3","objections":[{"q":"O celular com mapa offline não resolve?","a":"O celular tem bateria de horas. O Instinct 3 tem bateria de 26 dias. Em trilha longa, sem energia, o GPS integrado pode ser a diferença entre se perder ou não."},{"q":"O que é MIL-STD-810?","a":"É a certificação militar americana de resistência: testes de impacto, temperatura extrema, umidade, altitude e vibração."}]}'::jsonb, 3, true),
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'mulher-lifestyle', 'Mulher Lifestyle', 'Quer design elegante com funções inteligentes', '{"emoji":"💎","name":"Mulher Lifestyle","tag":"Quer design elegante com funções inteligentes","tags":["Lifestyle","Feminino","Design","Presente"],"sinais":["Pergunta por relógio menor ou mais bonito","Quer monitoramento de saúde feminina","Compra de presente para ela","Compara com Apple Watch no design"],"comunicacao":["Lily 2 — o menor e mais elegante da Garmin, design joia","Lily 2 Active — Lily com GPS integrado para quem corre ou caminha","Venu 4 — AMOLED premium com saúde feminina completa","O Garmin tem saúde feminina completa: ciclo, gravidez, menopausa"],"produtos":["Lily 2","Lily 2 Active","Venu 4"],"primario":"Lily 2 Active","objections":[{"q":"O Apple Watch tem mais funções de smartwatch.","a":"O Apple Watch tem um ecosistema forte, mas a bateria dura 1-2 dias com GPS. O Lily 2 Active tem GPS integrado e bateria de até 7 dias."},{"q":"Prefiro algo maior e mais completo.","a":"O Venu 4 tem tela AMOLED grande e premium, com todas as funções de saúde. Posso mostrar os dois para comparar no pulso?"}]}'::jsonb, 4, true),
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'ciclista', 'Ciclista', 'Pedala com frequência — estrada, MTB ou casual', '{"emoji":"🚴","name":"Ciclista","tag":"Pedala com frequência — estrada, MTB ou casual","tags":["Ciclismo","MTB","Estrada","Bike"],"sinais":["Menciona bike, MTB, estrada, gravel","Pergunta por GPS para guidão","Fala de Strava, Komoot, subidas","Quer medir cadência ou potência"],"comunicacao":["Edge 540/840 para quem quer GPS no guidão com tela maior","FR970 ou Fenix 8 para quem já tem relógio e quer multiesporte","Varia RTL515 — radar traseiro que detecta carros a 140m","Rally RK 200 — pedal medidor de potência SPD"],"produtos":["Edge 550","Edge 850","Edge 1050","Varia RTL515","Rally RK 200"],"primario":"Edge 850","objections":[{"q":"Uso o celular no suporte.","a":"O celular no sol laga, esquenta e a tela escurece. O Edge foi feito para isso: tela legível sob sol forte, modo específico para MTB e bateria que dura toda a etapa."},{"q":"Para que medidor de potência?","a":"Potência é a métrica mais honesta do ciclismo — não é afetada por cansaço, calor ou adrenalina."}]}'::jsonb, 5, true),
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'nadador-triatleta', 'Nadador / Triatleta', 'Nada regularmente ou compete em triathlon', '{"emoji":"🏊","name":"Nadador / Triatleta","tag":"Nada regularmente ou compete em triathlon","tags":["Natação","Piscina","Triathlon","Aquático"],"sinais":["Fala de piscina, mar, braçadas","Pergunta por relógio à prova d''água para natação","Quer SWOLF ou eficiência de braçada","Menciona triathlon ou duathlon"],"comunicacao":["FR970 ou FR965 — métricas completas de natação + ciclismo + corrida","Fenix 8 para o triatleta que quer o máximo","HRM 600 para registrar FC dentro da água","SWOLF: quanto menor, mais eficiente"],"produtos":["Forerunner 970","Forerunner 965","Fenix 8","HRM 600"],"primario":"Forerunner 970","objections":[{"q":"Não existe relógio que funcione bem na água.","a":"O Garmin têm resistência à água de 5 ATM. O FR970 reconhece automaticamente o tipo de braçada, conta voltas e mede SWOLF."}]}'::jsonb, 6, true),
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'mergulhador', 'Mergulhador', 'Pratica mergulho recreativo ou técnico', '{"emoji":"🤿","name":"Mergulhador","tag":"Pratica mergulho recreativo ou técnico","tags":["Mergulho","Dive","Aquático"],"sinais":["Menciona profundidade, descompressão, nitrox","Pergunta sobre computador de mergulho","Fala de mergulho técnico ou trimix"],"comunicacao":["Descent G1/G2 para mergulho recreativo","Descent Mk3i para técnico sério","Descent X30 com autonomia de gás e modo técnico","Destaque: smartwatch completo fora da água"],"produtos":["Descent G1","Descent G2","Descent Mk3i","Descent X30"],"primario":"Descent G2","objections":[{"q":"Prefiro um computador de mergulho separado.","a":"Computadores separados não têm GPS de superfície, mapas ou monitoramento de saúde. O Descent faz tudo isso e é um smartwatch completo no dia a dia."}]}'::jsonb, 7, true),
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'golfista', 'Golfista', 'Joga golfe com regularidade', '{"emoji":"⛳","name":"Golfista","tag":"Joga golfe com regularidade","tags":["Golfe","Golf"],"sinais":["Fala de green, par, bunker, handicap","Pergunta por GPS de golfe","Usa luvas de golfe ou tem look do esporte"],"comunicacao":["Approach S44 para entrada com +42.000 campos","Approach S50 para a experiência mais completa com AMOLED","Destaque distâncias automáticas do green","Scorecard digital e estatísticas de handicap"],"produtos":["Approach S44","Approach S50"],"primario":"Approach S50","objections":[{"q":"O app no celular já tem distâncias.","a":"O app serve, mas durante o swing você não vai olhar para o celular. O relógio no pulso mostra a distância instantaneamente, sem tirar o foco do jogo."}]}'::jsonb, 8, true),
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'motociclista', 'Motociclista', 'Piloto de moto, quer GPS robusto para viagens', '{"emoji":"🏍️","name":"Motociclista","tag":"Piloto de moto, quer GPS robusto para viagens","tags":["Moto","Viagem","GPS"],"sinais":["Fala de viagem de moto, rota, estrada","Pergunta por GPS para moto","Usa acessórios de motociclismo"],"comunicacao":["Zumo XT2 é o GPS específico para moto da Garmin","Tela resistente a luvas, antirreflexo, suporta chuva","Roteamento evita ruas proibidas para motos","Integração com capacete Bluetooth"],"produtos":["Zumo XT2"],"primario":"Zumo XT2","objections":[{"q":"O celular no suporte não é suficiente?","a":"O Zumo XT2 é feito para ser visto com luvas sob sol forte. Não esquenta, não buga, não depende de plano de dados."}]}'::jsonb, 9, true),
  ((select id from brands where slug = 'garmin'), 'perfil_cliente', 'pescador-nautico', 'Pescador / Náutico', 'Pesca em rios, represas ou mar', '{"emoji":"🎣","name":"Pescador / Náutico","tag":"Pesca em rios, represas ou mar","tags":["Pesca","Náutico","GPS"],"sinais":["Menciona pesca em represa, rio ou mar","Fala de barco, canoa, lancha","Pergunta sobre sonar ou ecobatímetro"],"comunicacao":["Striker 4 para pescador que quer o básico","Striker Vivid 5cv para quem quer ClearVü","ECHOMAP UHD2 para navegador sério com mapas náuticos","GPS marca os pontos de pesca para voltar depois"],"produtos":["Striker 4","Striker Vivid 5cv","ECHOMAP UHD2 52cv","GPSMAP 79","GPSMAP 86"],"primario":"Striker Vivid 5cv","objections":[{"q":"Uso o celular para mapas no barco.","a":"Celular não tem sonar e a tela não aguenta sol forte, maresia e vibrações. O Striker e ECHOMAP são feitos para isso."},{"q":"Preciso mesmo do ECHOMAP se o Vivid já tem GPS?","a":"O Vivid tem GPS básico. O ECHOMAP adiciona mapas náuticos detalhados com profundidade de canais e pontos de referência."}]}'::jsonb, 10, true)
on conflict (brand_id, category, slug) do nothing;

-- ============================================================================
-- 2. PRODUTOS (category = 'produto') — 53 itens do catálogo
-- ============================================================================
insert into content_library (brand_id, category, slug, title, summary, payload, order_index, is_published) values
  ((select id from brands where slug = 'garmin'), 'produto', 'forerunner-70', 'Forerunner 70', 'NOVO 2026.', '{"name":"Forerunner 70","s":"Forerunner","cat":"forerunner","lvl":1,"para":"Corredor Iniciante / Casual","dest":"NOVO 2026. GPS + cardíaco óptico + Garmin Pay. Design compacto e leve. Até 11 dias de bateria."}'::jsonb, 0, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'forerunner-55', 'Forerunner 55', 'GPS + cardíaco óptico.', '{"name":"Forerunner 55","s":"Forerunner","cat":"forerunner","lvl":1,"para":"Corredor Iniciante","dest":"GPS + cardíaco óptico. Porta de entrada para quem começa a correr."}'::jsonb, 1, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'forerunner-165', 'Forerunner 165', 'AMOLED + planos de treino adaptativos + treino de força.', '{"name":"Forerunner 165","s":"Forerunner","cat":"forerunner","lvl":2,"para":"Corredor Iniciante / Dedicado","dest":"AMOLED + planos de treino adaptativos + treino de força. Ótimo custo-benefício com tela premium."}'::jsonb, 2, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'forerunner-170', 'Forerunner 170', 'NOVO 2026.', '{"name":"Forerunner 170","s":"Forerunner","cat":"forerunner","lvl":2,"para":"Corredor Iniciante / Dedicado","dest":"NOVO 2026. AMOLED + Elevate Gen 4. Compacto (menor que o 165). Relatório noturno, despertador inteligente, registro de estilo de vida. Mais perfis de atividade. Sem multibanda. Sem triathlon (multiesporte a partir do 265)."}'::jsonb, 3, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'forerunner-265', 'Forerunner 265', 'AMOLED + GPS multibanda + Training Readiness.', '{"name":"Forerunner 265","s":"Forerunner","cat":"forerunner","lvl":3,"para":"Corredor Dedicado","dest":"AMOLED + GPS multibanda + Training Readiness. Melhor da faixa intermediária."}'::jsonb, 4, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'forerunner-570', 'Forerunner 570', 'Lançamento 2025.', '{"name":"Forerunner 570","s":"Forerunner","cat":"forerunner","lvl":3,"para":"Corredor Dedicado / Elite","dest":"Lançamento 2025. AMOLED + GPS SatIQ + Elevate Gen 5. Treino intervalado preciso."}'::jsonb, 5, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'forerunner-955', 'Forerunner 955', '30h GPS + mapas topográficos + solar.', '{"name":"Forerunner 955","s":"Forerunner","cat":"forerunner","lvl":4,"para":"Atleta de Elite / Triatleta","dest":"30h GPS + mapas topográficos + solar. Referência triatleta."}'::jsonb, 6, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'forerunner-965', 'Forerunner 965', 'AMOLED + titânio + mapas + 31h GPS.', '{"name":"Forerunner 965","s":"Forerunner","cat":"forerunner","lvl":4,"para":"Atleta de Elite / Triatleta","dest":"AMOLED + titânio + mapas + 31h GPS. Top de corrida com tela premium."}'::jsonb, 7, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'forerunner-970', 'Forerunner 970', 'Cristal safira + lanterna LED + 32GB.', '{"name":"Forerunner 970","s":"Forerunner","cat":"forerunner","lvl":5,"para":"Atleta de Elite","dest":"Cristal safira + lanterna LED + 32GB. Top absoluto da linha Forerunner."}'::jsonb, 8, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'fenix-e', 'Fenix E', 'Entrada da linha Fenix.', '{"name":"Fenix E","s":"Fenix","cat":"outdoor","lvl":3,"para":"Atleta / Aventureiro intermediário","dest":"Entrada da linha Fenix. AMOLED + GPS padrão + mapas TopoActive. Robusto, sem alto-falante/mic e sem GPS multibanda."}'::jsonb, 9, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'marq-commander-gen-2', 'MARQ Commander Gen 2', 'Luxo artesanal.', '{"name":"MARQ Commander Gen 2","s":"MARQ","cat":"luxo","lvl":5,"para":"Executivo / Atleta premium","dest":"Luxo artesanal. Titânio + safira + couro italiano. Estética tática, GPS multibanda, mapas completos."}'::jsonb, 10, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'marq-athlete-gen-2', 'MARQ Athlete Gen 2', 'Luxo para corrida e triathlon.', '{"name":"MARQ Athlete Gen 2","s":"MARQ","cat":"luxo","lvl":5,"para":"Atleta premium / Executivo esportivo","dest":"Luxo para corrida e triathlon. Titânio + safira. GPS multibanda e métricas avançadas com acabamento de alto nível."}'::jsonb, 11, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'marq-golfer-carbon-gen-2', 'MARQ Golfer Carbon Gen 2', 'Único relógio de golfe no nível de luxo real.', '{"name":"MARQ Golfer Carbon Gen 2","s":"MARQ","cat":"luxo","lvl":5,"para":"Golfista premium","dest":"Único relógio de golfe no nível de luxo real. Fibra de carbono + safira + 42.000 campos mapeados."}'::jsonb, 12, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'fenix-8', 'Fenix 8', 'O multiesporte definitivo.', '{"name":"Fenix 8","s":"Fenix","cat":"outdoor","lvl":5,"para":"Atleta Elite / Aventureiro","dest":"O multiesporte definitivo. Alto-falante, mic, mergulho, trilha, corrida."}'::jsonb, 13, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'enduro-3', 'Enduro 3', 'Bateria 70h+ GPS.', '{"name":"Enduro 3","s":"Enduro","cat":"outdoor","lvl":5,"para":"Ultra / Expedição","dest":"Bateria 70h+ GPS. Para ultramaratonistas e expedições longas."}'::jsonb, 14, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'instinct-3', 'Instinct 3', 'MIL-STD-810.', '{"name":"Instinct 3","s":"Instinct","cat":"outdoor","lvl":3,"para":"Aventureiro / Corredor","dest":"MIL-STD-810. Bateria até 26 dias. Custo-benefício outdoor."}'::jsonb, 15, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'instinct-e', 'Instinct E', 'Versão entrada do Instinct.', '{"name":"Instinct E","s":"Instinct","cat":"outdoor","lvl":2,"para":"Aventureiro Iniciante","dest":"Versão entrada do Instinct. Robustez com preço acessível."}'::jsonb, 16, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'instinct-crossover', 'Instinct Crossover', 'GPS + ponteiros analógicos.', '{"name":"Instinct Crossover","s":"Instinct","cat":"outdoor","lvl":3,"para":"Aventureiro / Lifestyle","dest":"GPS + ponteiros analógicos. Estética clássica + tecnologia."}'::jsonb, 17, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'venu-4', 'Venu 4', 'AMOLED premium + saúde feminina completa.', '{"name":"Venu 4","s":"Venu","cat":"lifestyle","lvl":3,"para":"Mulher Lifestyle / Bem-estar","dest":"AMOLED premium + saúde feminina completa. Até 9 dias de bateria."}'::jsonb, 18, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'venu-x1', 'Venu X1', 'Design quadrado moderno.', '{"name":"Venu X1","s":"Venu","cat":"lifestyle","lvl":4,"para":"Lifestyle Premium","dest":"Design quadrado moderno. Para quem quer visual tipo Apple Watch."}'::jsonb, 19, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'vivoactive-6', 'Vivoactive 6', '80+ modos esportivos + músicas offline.', '{"name":"Vivoactive 6","s":"Vivoactive","cat":"lifestyle","lvl":2,"para":"Academia / Lifestyle","dest":"80+ modos esportivos + músicas offline. Versátil para academia e dia a dia."}'::jsonb, 20, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'lily-2', 'Lily 2', 'Design joia.', '{"name":"Lily 2","s":"Lily","cat":"lifestyle","lvl":1,"para":"Mulher Lifestyle / Presente","dest":"Design joia. Menor relógio Garmin. Elegância e saúde no pulso."}'::jsonb, 21, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'lily-2-active', 'Lily 2 Active', 'Lily com GPS integrado + resistência à água.', '{"name":"Lily 2 Active","s":"Lily","cat":"lifestyle","lvl":2,"para":"Mulher Lifestyle / Corrida","dest":"Lily com GPS integrado + resistência à água. Corrida + estilo."}'::jsonb, 22, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'descent-g1', 'Descent G1', 'Entrada no mundo Descent.', '{"name":"Descent G1","s":"Descent","cat":"mergulho","lvl":2,"para":"Mergulhador Recreativo","dest":"Entrada no mundo Descent. Dive watch + GPS. Recreativo até 100m."}'::jsonb, 23, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'descent-g2', 'Descent G2', 'Multigas + AMOLED + GPS.', '{"name":"Descent G2","s":"Descent","cat":"mergulho","lvl":3,"para":"Mergulhador Recreativo / Avançado","dest":"Multigas + AMOLED + GPS. Melhor custo-benefício Descent."}'::jsonb, 24, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'descent-mk3i', 'Descent Mk3i', 'Titânio + AMOLED + multibanda.', '{"name":"Descent Mk3i","s":"Descent","cat":"mergulho","lvl":4,"para":"Mergulhador Técnico","dest":"Titânio + AMOLED + multibanda. Para mergulhadores técnicos sérios."}'::jsonb, 25, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'descent-x30', 'Descent X30', 'Autonomia de gás + trimix + modo técnico avançado.', '{"name":"Descent X30","s":"Descent","cat":"mergulho","lvl":5,"para":"Mergulhador Técnico Avançado","dest":"Autonomia de gás + trimix + modo técnico avançado."}'::jsonb, 26, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'edge-540', 'Edge 540', 'GPS multibanda + botões físicos.', '{"name":"Edge 540","s":"Edge","cat":"edge","lvl":2,"para":"Ciclista Intermediário","dest":"GPS multibanda + botões físicos. Bateria 26h. Compacto e preciso."}'::jsonb, 27, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'edge-550', 'Edge 550', '2025.', '{"name":"Edge 550","s":"Edge","cat":"edge","lvl":2,"para":"Ciclista / Tela Brilhante","dest":"2025. Tela 1000 nits + speaker + Cycling Coach. Sucessor do 540."}'::jsonb, 28, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'edge-840', 'Edge 840', 'Touchscreen + botões + GPS multibanda + ClimbPro.', '{"name":"Edge 840","s":"Edge","cat":"edge","lvl":3,"para":"Ciclista Dedicado","dest":"Touchscreen + botões + GPS multibanda + ClimbPro. Ideal para MTB e estrada."}'::jsonb, 29, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'edge-850', 'Edge 850', '2025.', '{"name":"Edge 850","s":"Edge","cat":"edge","lvl":3,"para":"Ciclista Dedicado / Avançado","dest":"2025. Tela 1000 nits + speaker + bike bell. Versão compacta do 1050."}'::jsonb, 30, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'edge-1040', 'Edge 1040', 'Tela 3.5" + mapas + solar disponível.', '{"name":"Edge 1040","s":"Edge","cat":"edge","lvl":4,"para":"Ciclista Avançado","dest":"Tela 3.5\" + mapas + solar disponível. Bateria 35h+ GPS."}'::jsonb, 31, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'edge-1050', 'Edge 1050', 'Tela 3.5" 1000 nits + Garmin Pay + buzina + alerta de perigo.', '{"name":"Edge 1050","s":"Edge","cat":"edge","lvl":5,"para":"Ciclista Elite","dest":"Tela 3.5\" 1000 nits + Garmin Pay + buzina + alerta de perigo."}'::jsonb, 32, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'gpsmap-65', 'GPSMAP 65', 'GPS portátil colorido + multibanda.', '{"name":"GPSMAP 65","s":"GPSMAP","cat":"gps","lvl":3,"para":"Trilheiro / Aventureiro","dest":"GPS portátil colorido + multibanda. Botões físicos. Carregamento USB."}'::jsonb, 33, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'gpsmap-67', 'GPSMAP 67', 'Tela 3" + TopoActive Brasil + altímetro + bússola + USB-C.', '{"name":"GPSMAP 67","s":"GPSMAP","cat":"gps","lvl":4,"para":"Aventureiro / Expedição","dest":"Tela 3\" + TopoActive Brasil + altímetro + bússola + USB-C. O mais completo."}'::jsonb, 34, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'gpsmap-79', 'GPSMAP 79', 'GPS portátil flutuante para uso náutico.', '{"name":"GPSMAP 79","s":"GPSMAP","cat":"gps","lvl":3,"para":"Pescador / Náutico","dest":"GPS portátil flutuante para uso náutico. Mapas BlueChart."}'::jsonb, 35, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'gpsmap-86', 'GPSMAP 86', 'GPS náutico flutuante 3" + bússola + barômetro.', '{"name":"GPSMAP 86","s":"GPSMAP","cat":"gps","lvl":3,"para":"Náutico / Marinheiro","dest":"GPS náutico flutuante 3\" + bússola + barômetro. Para embarcações."}'::jsonb, 36, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'etrex-22x', 'eTrex 22x', 'Entrada da linha eTrex.', '{"name":"eTrex 22x","s":"eTrex","cat":"gps","lvl":1,"para":"Caminhante / Iniciante","dest":"Entrada da linha eTrex. Robusto, simples, mapas TopoActive. Bateria AA."}'::jsonb, 37, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'etrex-32x', 'eTrex 32x', 'eTrex 22x + bússola 3 eixos + altímetro barométrico.', '{"name":"eTrex 32x","s":"eTrex","cat":"gps","lvl":2,"para":"Trilheiro / Trekking","dest":"eTrex 22x + bússola 3 eixos + altímetro barométrico. Bússola real."}'::jsonb, 38, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'etrex-solar', 'eTrex Solar', 'Carregamento solar + bateria de até 100h.', '{"name":"eTrex Solar","s":"eTrex","cat":"gps","lvl":3,"para":"Expedição / Ultra","dest":"Carregamento solar + bateria de até 100h. Para expedições longas."}'::jsonb, 39, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'inreach-mini-2', 'inReach Mini 2', 'Comunicador satélite bidirecional.', '{"name":"inReach Mini 2","s":"inReach","cat":"gps","lvl":3,"para":"Aventureiro / Expedição","dest":"Comunicador satélite bidirecional. SOS + mensagens sem sinal de celular."}'::jsonb, 40, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'inreach-mini-3', 'inReach Mini 3', 'Mini 2 + tela colorida touch + GPS multibanda + sirene.', '{"name":"inReach Mini 3","s":"inReach","cat":"gps","lvl":3,"para":"Aventureiro / Expedição","dest":"Mini 2 + tela colorida touch + GPS multibanda + sirene. Versão atual."}'::jsonb, 41, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'inreach-mini-3-plus', 'inReach Mini 3 Plus', 'Mini 3 + mensagens de voz (30s) + fotos via satélite.', '{"name":"inReach Mini 3 Plus","s":"inReach","cat":"gps","lvl":4,"para":"Profissional / Expedição","dest":"Mini 3 + mensagens de voz (30s) + fotos via satélite."}'::jsonb, 42, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'approach-s44', 'Approach S44', '+42.000 campos.', '{"name":"Approach S44","s":"Approach","cat":"golf","lvl":2,"para":"Golfista Iniciante","dest":"+42.000 campos. Distâncias automáticas. Entrada ideal no golfe Garmin."}'::jsonb, 43, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'approach-s50', 'Approach S50', 'AMOLED + +42.000 campos + visão aérea.', '{"name":"Approach S50","s":"Approach","cat":"golf","lvl":3,"para":"Golfista Dedicado","dest":"AMOLED + +42.000 campos + visão aérea. Melhor experiência de golfe."}'::jsonb, 44, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'zumo-xt2', 'Zumo XT2', 'GPS para moto.', '{"name":"Zumo XT2","s":"Zumo","cat":"moto","lvl":4,"para":"Motociclista","dest":"GPS para moto. Tela resistente a luvas, chuva e sol. Roteamento anti-pedágio."}'::jsonb, 45, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'striker-4', 'Striker 4', 'Sonar 3.5" com GPS básico.', '{"name":"Striker 4","s":"Striker","cat":"marine","lvl":1,"para":"Pescador Iniciante","dest":"Sonar 3.5\" com GPS básico. Entrada acessível para pesca."}'::jsonb, 46, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'striker-vivid-5cv', 'Striker Vivid 5cv', 'Sonar 5" colorido + ClearVü + GPS.', '{"name":"Striker Vivid 5cv","s":"Striker","cat":"marine","lvl":2,"para":"Pescador","dest":"Sonar 5\" colorido + ClearVü + GPS. Ótimo custo-benefício."}'::jsonb, 47, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'echomap-uhd2-52cv', 'ECHOMAP UHD2 52cv', 'Chartplotter + sonar UHD2 5".', '{"name":"ECHOMAP UHD2 52cv","s":"ECHOMAP","cat":"marine","lvl":3,"para":"Pescador/Navegador","dest":"Chartplotter + sonar UHD2 5\". Mapas BlueChart G3."}'::jsonb, 48, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'hrm-200', 'HRM 200', 'Monitor cardíaco de peito.', '{"name":"HRM 200","s":"HRM","cat":"acess","lvl":2,"para":"Corredor / Ciclista","dest":"Monitor cardíaco de peito. Precisão superior ao óptico de pulso."}'::jsonb, 49, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'hrm-600', 'HRM 600', 'Monitor cardíaco premium com dinâmicas de corrida, HRV e armazenamento.', '{"name":"HRM 600","s":"HRM","cat":"acess","lvl":4,"para":"Corredor / Nadador / Triatleta","dest":"Monitor cardíaco premium com dinâmicas de corrida, HRV e armazenamento."}'::jsonb, 50, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'varia-rtl515', 'Varia RTL515', 'Radar traseiro + luz.', '{"name":"Varia RTL515","s":"Varia","cat":"acess","lvl":3,"para":"Ciclista","dest":"Radar traseiro + luz. Detecta veículos a 140m e alerta no relógio."}'::jsonb, 51, true),
  ((select id from brands where slug = 'garmin'), 'produto', 'rally-rk-200', 'Rally RK 200', 'Pedal medidor de potência SPD.', '{"name":"Rally RK 200","s":"Rally","cat":"acess","lvl":4,"para":"Ciclista de Performance","dest":"Pedal medidor de potência SPD. Compatível com qualquer pedivela."}'::jsonb, 52, true)
on conflict (brand_id, category, slug) do nothing;

-- ============================================================================
-- 3. FAQ (category = 'faq') — 16 perguntas frequentes
-- ============================================================================
insert into content_library (brand_id, category, slug, title, summary, payload, order_index, is_published) values
  ((select id from brands where slug = 'garmin'), 'faq', 'qual-a-diferenca-entre-garmin-connect-e-connect-iq', 'Qual a diferença entre Garmin Connect e Connect IQ?', 'Garmin Connect é o app de sincronização — recebe dados do relógio e integra com Strava, Apple Health etc.', '{"q":"Qual a diferença entre Garmin Connect e Connect IQ?","a":"Garmin Connect é o app de sincronização — recebe dados do relógio e integra com Strava, Apple Health etc. Connect IQ é a loja de apps que rodam DENTRO do relógio, como Spotify, Wikiloc e Woo."}'::jsonb, 0, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'o-garmin-tem-spotify', 'O Garmin tem Spotify?', 'Sim!', '{"q":"O Garmin tem Spotify?","a":"Sim! Nos modelos com armazenamento interno (FR265, 570, 955, 965, 970, Fenix 8, Venu 4 e outros). Baixe o app Spotify pela Connect IQ Store, sincronize playlists via Wi-Fi e ouça offline com fones Bluetooth."}'::jsonb, 1, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'o-garmin-funciona-sem-celular', 'O Garmin funciona sem celular?', 'Sim.', '{"q":"O Garmin funciona sem celular?","a":"Sim. O GPS é embutido no relógio. Você sai para correr sem celular e registra todos os dados. A sincronização acontece depois, quando você conecta via Bluetooth."}'::jsonb, 2, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'quanto-tempo-dura-a-bateria', 'Quanto tempo dura a bateria?', 'Em smartwatch (sem GPS): FR55 ~2 semanas, Instinct 3 ~26 dias, Fenix 8 ~18 dias.', '{"q":"Quanto tempo dura a bateria?","a":"Em smartwatch (sem GPS): FR55 ~2 semanas, Instinct 3 ~26 dias, Fenix 8 ~18 dias. Em GPS ativo: FR55 ~20h, FR955 ~30h, Enduro 3 ~70h. OBS: GPS multibanda consome ~30-40% mais."}'::jsonb, 3, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'qual-a-diferenca-entre-gps-multibanda-e-gps-comum', 'Qual a diferença entre GPS multibanda e GPS comum?', 'O GPS comum usa uma frequência de satélite.', '{"q":"Qual a diferença entre GPS multibanda e GPS comum?","a":"O GPS comum usa uma frequência de satélite. O multibanda usa duas (L1 e L5) simultaneamente, resultando em traçado muito mais preciso em cidades com prédios, florestas e montanhas."}'::jsonb, 4, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'o-sensor-de-fc-no-pulso-e-preciso', 'O sensor de FC no pulso é preciso?', 'Preciso em intensidade moderada.', '{"q":"O sensor de FC no pulso é preciso?","a":"Preciso em intensidade moderada. Em atividades de alta intensidade, recomendamos o HRM de peito (HRM 200 ou HRM 600) para máxima precisão."}'::jsonb, 5, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'o-que-e-o-vo2-max-da-garmin', 'O que é o VO2 Max da Garmin?', 'Estimativa do consumo máximo de oxigênio calculada pelo algoritmo FirstBeat, baseada na relação entre FC e velocidade.', '{"q":"O que é o VO2 Max da Garmin?","a":"Estimativa do consumo máximo de oxigênio calculada pelo algoritmo FirstBeat, baseada na relação entre FC e velocidade. É um excelente indicador de evolução aeróbica."}'::jsonb, 6, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'o-que-e-o-body-battery', 'O que é o Body Battery?', 'Indicador de energia de 0-100 baseado em HRV, sono, estresse e atividade.', '{"q":"O que é o Body Battery?","a":"Indicador de energia de 0-100 baseado em HRV, sono, estresse e atividade. Sobe com sono de qualidade, cai com estresse e exercício. Ajuda o atleta a saber o melhor momento para treinar."}'::jsonb, 7, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'o-garmin-monitora-sono', 'O Garmin monitora sono?', 'Sim.', '{"q":"O Garmin monitora sono?","a":"Sim. Todos os modelos com sensor de FC monitoram sono automaticamente: fases (leve, profundo, REM), SpO2 noturno e pontuação de sono. Dados disponíveis no Garmin Connect pela manhã."}'::jsonb, 8, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'o-garmin-funciona-com-android-e-iphone', 'O Garmin funciona com Android e iPhone?', 'Sim.', '{"q":"O Garmin funciona com Android e iPhone?","a":"Sim. O Garmin Connect é compatível com iOS e Android. Apple Health sincroniza apenas em iPhones."}'::jsonb, 9, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'o-garmin-tem-nfc-para-pagamento', 'O Garmin tem NFC para pagamento?', 'Sim, via Garmin Pay nos modelos compatíveis: Fenix 8, FR265, 570, 955, 965, 970, Venu 4, Vivoactive 6 e outros.', '{"q":"O Garmin tem NFC para pagamento?","a":"Sim, via Garmin Pay nos modelos compatíveis: Fenix 8, FR265, 570, 955, 965, 970, Venu 4, Vivoactive 6 e outros."}'::jsonb, 10, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'qual-a-garantia-oferecida-pela-proparts', 'Qual a garantia oferecida pela Proparts?', 'A Proparts oferece 2 anos de garantia para todos os dispositivos Garmin e 1 ano para acessórios.', '{"q":"Qual a garantia oferecida pela Proparts?","a":"A Proparts oferece 2 anos de garantia para todos os dispositivos Garmin e 1 ano para acessórios. Para acionar, é necessário apenas o cadastro completo no sistema."}'::jsonb, 11, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'o-edge-e-diferente-do-relogio-para-ciclismo', 'O Edge é diferente do relógio para ciclismo?', 'Sim.', '{"q":"O Edge é diferente do relógio para ciclismo?","a":"Sim. O Edge é um ciclocomputador fixado no guidão — tela maior, ideal para ver dados em velocidade. Relógios como FR965 ou Fenix 8 também registram ciclismo com precisão."}'::jsonb, 12, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'o-inreach-mini-precisa-de-assinatura-para-funcionar', 'O inReach Mini precisa de assinatura para funcionar?', 'Sim.', '{"q":"O inReach Mini precisa de assinatura para funcionar?","a":"Sim. Sem assinatura ativa, as funções via satélite ficam desativadas. Existe o plano Enabled (~US$7,99/mês) para SOS de emergência. É possível suspender por até 12 meses sem custo."}'::jsonb, 13, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'qual-a-diferenca-entre-hrm-200-e-hrm-600', 'Qual a diferença entre HRM 200 e HRM 600?', 'O HRM 200 é para corrida e ciclismo — não armazena atividades.', '{"q":"Qual a diferença entre HRM 200 e HRM 600?","a":"O HRM 200 é para corrida e ciclismo — não armazena atividades. O HRM 600 é para corrida, natação e triatlo — armazena as atividades internamente, inclusive embaixo da água."}'::jsonb, 14, true),
  ((select id from brands where slug = 'garmin'), 'faq', 'qual-rede-de-satelites-o-inreach-utiliza', 'Qual rede de satélites o inReach utiliza?', 'O inReach usa a rede de satélites Iridium®, que oferece cobertura global de 100% do planeta — incluindo oceanos, polos e áreas sem qualquer cobertura de celular.', '{"q":"Qual rede de satélites o inReach utiliza?","a":"O inReach usa a rede de satélites Iridium®, que oferece cobertura global de 100% do planeta — incluindo oceanos, polos e áreas sem qualquer cobertura de celular."}'::jsonb, 15, true)
on conflict (brand_id, category, slug) do nothing;

-- ============================================================================
-- 4. CONCORRENTES (category = 'concorrente') — 5 comparativos
-- ============================================================================
insert into content_library (brand_id, category, slug, title, summary, payload, order_index, is_published) values
  ((select id from brands where slug = 'garmin'), 'concorrente', 'apple-watch', 'Apple Watch', 'O concorrente mais citado.', '{"name":"Apple Watch","badge":"⚠️ Principal","bc":"orange","desc":"O concorrente mais citado. Forte em design e integração com iPhone. Fraco em bateria e precisão esportiva.","rows":[{"a":"Bateria GPS","g":"30h+ (FR955) / 70h (Enduro)","t":"~6-18h dependendo do modelo"},{"a":"Precisão GPS","g":"Multibanda + múltiplos satélites","t":"GPS básico (Ultra tem dual frequency)"},{"a":"Foco esportivo","g":"Ferramenta de atleta — FirstBeat","t":"Smartwatch com função esportiva"},{"a":"Bateria diária","g":"Dias ou semanas","t":"1-2 dias"},{"a":"Compatibilidade","g":"iOS e Android","t":"Exclusivo iPhone"}]}'::jsonb, 0, true),
  ((select id from brands where slug = 'garmin'), 'concorrente', 'polar', 'Polar', 'Referência em análise científica de treino.', '{"name":"Polar","badge":"⚠️ Principal","bc":"orange","desc":"Referência em análise científica de treino. Boa análise, mas ecossistema menor.","rows":[{"a":"Análise de treino","g":"FirstBeat — líder de mercado","t":"Excelente — base acadêmica"},{"a":"GPS","g":"Multibanda nos modelos avançados","t":"Preciso mas sem multibanda na maioria"},{"a":"Apps no relógio","g":"Connect IQ com centenas de apps","t":"Ecossistema menor"},{"a":"Bateria","g":"Dias ou semanas","t":"Até ~40h GPS nos top"}]}'::jsonb, 1, true),
  ((select id from brands where slug = 'garmin'), 'concorrente', 'coros', 'Coros', 'Marca chinesa com preço agressivo.', '{"name":"Coros","badge":"⚡ Crescente","bc":"blue","desc":"Marca chinesa com preço agressivo. Principal argumento do cliente sensível a preço.","rows":[{"a":"Preço","g":"Premium — qualidade justifica","t":"Até 30-40% mais barato"},{"a":"Ecossistema","g":"Connect IQ + 50+ integrações","t":"Ecossistema em desenvolvimento"},{"a":"Suporte no Brasil","g":"Rede oficial Proparts","t":"Suporte mais limitado"},{"a":"Histórico","g":"+35 anos no mercado","t":"Marca recente (2012)"}]}'::jsonb, 2, true),
  ((select id from brands where slug = 'garmin'), 'concorrente', 'samsung-galaxy-watch', 'Samsung Galaxy Watch', 'Forte em design e Android.', '{"name":"Samsung Galaxy Watch","badge":"💡 Lifestyle","bc":"blue","desc":"Forte em design e Android. Não compete em esporte de performance.","rows":[{"a":"Bateria","g":"Dias ou semanas com GPS","t":"1-3 dias com GPS ativo"},{"a":"Esportes avançados","g":"Algoritmos específicos por modalidade","t":"Modo esportivo básico"},{"a":"Compatibilidade","g":"iOS e Android","t":"Melhor com Samsung Android"}]}'::jsonb, 3, true),
  ((select id from brands where slug = 'garmin'), 'concorrente', 'suunto', 'Suunto', 'Herança em outdoor e mergulho.', '{"name":"Suunto","badge":"🌿 Nicho Outdoor","bc":"blue","desc":"Herança em outdoor e mergulho. Qualidade, mas ecossistema menor.","rows":[{"a":"Outdoor / Trilha","g":"Fenix 8, Instinct 3 — referência","t":"Suunto 9 é boa proposta"},{"a":"Mergulho","g":"Série Descent — mais completa","t":"Tradição em dive computers"},{"a":"Integrações","g":"Connect IQ + dezenas","t":"Ecossistema mais limitado"},{"a":"Distribuição BR","g":"Rede Proparts ampla","t":"Distribuição mais restrita"}]}'::jsonb, 4, true)
on conflict (brand_id, category, slug) do nothing;

-- ============================================================================
-- 5. ESPECIALIDADES POR ESPORTE (category = 'especialidade') — 10 esportes
-- ============================================================================
insert into content_library (brand_id, category, slug, title, summary, payload, order_index, is_published) values
  ((select id from brands where slug = 'garmin'), 'especialidade', 'corrida', 'Corrida', '12 métricas registradas, incluindo Distância', '{"emoji":"🏃","name":"Corrida","metrics":["Distância","Ritmo (min/km)","Cadência (passos/min)","Tempo de contato com solo","FC","Extensão da passada","Oscilação vertical","PacePRO","Potência de corrida","Elevação","VO2 Max estimado","Training Effect"]}'::jsonb, 0, true),
  ((select id from brands where slug = 'garmin'), 'especialidade', 'ciclismo', 'Ciclismo', '8 métricas registradas, incluindo Distância', '{"emoji":"🚴","name":"Ciclismo","metrics":["Distância","Velocidade (atual/média/máx)","Cadência (RPM)","Elevação acumulada","Potência (com pedal Rally)","FTP estimado","FC","Training Load"]}'::jsonb, 1, true),
  ((select id from brands where slug = 'garmin'), 'especialidade', 'natacao', 'Natação', '6 métricas registradas, incluindo Distância', '{"emoji":"🏊","name":"Natação","metrics":["Distância","Ritmo (min/100m)","Frequência de braçadas","Tipo de braçada (crawl, costas, peito, borboleta)","SWOLF (eficiência)","Tempo de descanso entre séries"]}'::jsonb, 2, true),
  ((select id from brands where slug = 'garmin'), 'especialidade', 'academia-forca', 'Academia / Força', '5 métricas registradas, incluindo Séries e repetições (detecção automática)', '{"emoji":"💪","name":"Academia / Força","metrics":["Séries e repetições (detecção automática)","Calorias ativas","Mapa muscular","FC","Tempo de descanso"]}'::jsonb, 3, true),
  ((select id from brands where slug = 'garmin'), 'especialidade', 'trilha-trekking', 'Trilha / Trekking', '7 métricas registradas, incluindo Distância', '{"emoji":"🥾","name":"Trilha / Trekking","metrics":["Distância","Subida total acumulada","Velocidade média","FC","Elevação atual","Mapa topográfico (modelos compatíveis)","Wikiloc / Komoot integrado"]}'::jsonb, 4, true),
  ((select id from brands where slug = 'garmin'), 'especialidade', 'surf', 'Surf', '5 métricas registradas, incluindo Número de ondas', '{"emoji":"🏄","name":"Surf","metrics":["Número de ondas","Velocidade máxima","Distância em ondas","Tempo de sessão","FC"]}'::jsonb, 5, true),
  ((select id from brands where slug = 'garmin'), 'especialidade', 'kitesurf', 'Kitesurf', '5 métricas registradas, incluindo Distância total', '{"emoji":"🪁","name":"Kitesurf","metrics":["Distância total","FC","Velocidade máxima","Altura de saltos em tempo real (app Woo)","Dados de sessão via Hoolan"]}'::jsonb, 6, true),
  ((select id from brands where slug = 'garmin'), 'especialidade', 'golfe', 'Golfe', '5 métricas registradas, incluindo Scorecard digital', '{"emoji":"⛳","name":"Golfe","metrics":["Scorecard digital","Distância até frente/meio/fundo do green","Detecção automática de tacadas","Handicap","Par do buraco"]}'::jsonb, 7, true),
  ((select id from brands where slug = 'garmin'), 'especialidade', 'mergulho-descent', 'Mergulho (Descent)', '8 métricas registradas, incluindo Profundidade atual e máxima', '{"emoji":"🤿","name":"Mergulho (Descent)","metrics":["Profundidade atual e máxima","Tempo de fundo","NDL (limite sem descompressão)","Temperatura da água","Algoritmo Bühlmann","Modo Nitrox","Autonomia de gás (X30)","Modo apneia"]}'::jsonb, 8, true),
  ((select id from brands where slug = 'garmin'), 'especialidade', 'moto-zumo-xt2', 'Moto (Zumo XT2)', '4 métricas registradas, incluindo Roteamento específico para moto', '{"emoji":"🏍️","name":"Moto (Zumo XT2)","metrics":["Roteamento específico para moto","Evita estradas proibidas","Integração capacete Bluetooth","Rastreamento de rota"]}'::jsonb, 9, true)
on conflict (brand_id, category, slug) do nothing;

-- ============================================================================
-- FIM DA SEED 040
-- ============================================================================
